# Generated by Django 4.2.2 on 2023-06-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_name', models.CharField(blank=True, help_text='Stroring the Name of resident', max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('resident_building_name', models.CharField(blank=True, help_text='Storing residence building name', max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('token_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('move_out_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
