# Generated by Django 4.2.2 on 2023-06-09 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('activites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityevents',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employeer'),
        ),
    ]
